# GAME STATES
MAIN_MENU = "MAIN_MENU"
PLAYING = "PLAYING"
GAME_OVER = "GAME_OVER"
QUIT = "QUIT"

# DIFFICULTIES
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
DEFAULT_DIFFICULTY = DIFFICULTY_NORMAL