# GAME
FPS = 60
WINDOW_SIZE: tuple[int, int] = (1280, 720)

# CINEMATIC STATES
INTRO_WAITING = "WAITING"
INTRO_FINISHED = "FINISHED"
INTRO_RUNNING = "RUNNING"

# GAME STATES
INTRO = "INTRO"
LANDING_MENU = "LANDING_MENU"
MAIN_MENU = "MAIN_MENU"
PLAYING = "PLAYING"
GAME_OVER = "GAME_OVER"
QUIT = "QUIT"

# PLAYER SETTINGS
PLAYER_SIZE = (128, 128)
PLAYER_HB_SIZE = (25, 50)
PLAYER_ANIM_OFFSET_Y = -20

# ENTITY STATES
IDLE = "IDLE"
WALK = "WALK"
RUN = "RUN"
JUMP_START = "JUMP_START"
JUMP_TRANSITION = "JUMP_TRANSITION"
JUMP = "JUMP"
JUMP_FALL = "JUMP_FALL"
ATTACK = "ATTACK"
HURT = "HURT"
DASH = "DASH"
HEALING = "HEALING"

# PLATORME TYPES
SOLID = "SOLID"
TAVERSABLE = "TRAVERSABLE"

# DIFFICULTY
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
DEFAULT_DIFFICULTY = DIFFICULTY_NORMAL

# WORLD
MAPS_BASEURL = "assets/world/maps/{}.tmx"
MAPS = ["map01"]
MAPS_OFFSET_Y = 310
GROUND_LAYER = "ground"